server:  
  port: ${PORT:9999}
  servlet:
    session:
      cookie:
        name: SSO-SESSION
  ssl:
    enabled: ${SSL_ENABLED:false}
    key-alias: ${SSL_KEY_ALIAS}
    key-store: ${SSL_KEY_STORE}
    key-store-password: ${SSL_KEY_STORE_PASSWORD}
  
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka/}

spring:  
  application:
    name: sso-service
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: lecom
    driver-class-name: com.mysql.jdbc.Driver
    schema: classpath:/script/schema.sql
    data: classpath:/script/data.sql
    
logging:
  level:
    org.springframework.security: DEBUG
